const BLOG_CONTENTS_LOCATION = "blog-contents"
const BLOG_POST_CONTENTS_LOCATION = `${BLOG_CONTENTS_LOCATION}/contents`
const BLOG_AUTHOR_CONTENTS_LOCATION = `${BLOG_CONTENTS_LOCATION}/author`

export { BLOG_POST_CONTENTS_LOCATION, BLOG_AUTHOR_CONTENTS_LOCATION }
